### ISSUE TITLE
How should division be parsed?

### ISSUE THREAD

**Issue by k4b7** [kevinbarabash/math-parser#16]
current behavior: `1 * 2 / 3 => (1 * 2) / 3`
proposed behavior: `1 * 2 / 3 => 1 * (2 / 3)`

current behavior: `1 / 2 / 3 => 1 / (2 * 3)`
proposed behavior: `1 / 2 / 3 => (1 / 2) / 3`

**Comment by k4b7** [comment]
Also, 
```
a / b / c / d => ((a / b) / c) / d
a * b / c * d => a * (b/c) * d
a * b * c / d => a * b * (c/d)
```

@evykassirer @aelnaiem does that match your understanding of how fractions should be parsed?

**Comment by evykassirer** [comment]
Are these differences from mathjs?

I think `1 / 2 / 3 => 1 / (2 * 3)` is an actual step we do in mathsoc, and not something mathjs does

**Comment by evykassirer** [comment]
I agree with everything you say about parsing in terms of tree structure (though not necessarily writing in the explicit parentheses)

I thought mathjs did that in their parsing though, so I'm confused about what you mean by current behavior

**Comment by k4b7** [comment]
@evykassirer cool.  The parens are there to show the structure only.  What I mean by "current" behavior was current __`math-parser`__ behavior.  I want to align with whatever `mathsteps` is doing.

I'm seeing:
```
const steps = mathsteps.simplifyExpression('a / b / c + 0');
console.log(JSON.stringify(steps[0].newNode, null, 4));

{
    "implicit": false,
    "op": "/",
    "fn": "divide",
    "args": [
        {
            "implicit": false,
            "op": "/",
            "fn": "divide",
            "args": [
                {
                    "name": "a"
                },
                {
                    "name": "b"
                }
            ]
        },
        {
            "name": "c"
        }
    ],
    "changeGroup": 1
}
```

**Comment by evykassirer** [comment]
ahh, ok.

perfect then!

**Comment by tkosan** [comment]
This is how MathPiper/YACAS parses these expressions:

`In> UnparseMathPiper('( 1*2/3 ), FullParentheses:True)`
`Result: "(1*(2/3))"`

`In> UnparseMathPiper('( 1/2/3 ), FullParentheses:True)`
`Result: "((1/2)/3)"`

`In> UnparseMathPiper('( a / b / c / d ), FullParentheses:True)`
`Result: "(((a/b)/c)/d)"`

`In> UnparseMathPiper('( a * b / c * d), FullParentheses:True)`
`Result: "((a*(b/c))*d)"`

`In> UnparseMathPiper('( a * b * c / d ), FullParentheses:True)`
`Result: "((a*b)*(c/d))"`

**Comment by evykassirer** [comment]
that's all same as mathjs right?

**Comment by tkosan** [comment]
Here is the same information as above with mathjs included:

`In> UnparseMathPiper('( 1*2/3 ), FullParentheses:True)`
`Result: "(1*(2/3))"`
`mathjs: (/ (* 1 2) 3)`

`In> UnparseMathPiper('( 1/2/3 ), FullParentheses:True)`
`Result: "((1/2)/3)"`
`mathjs: (/ (/ 1 2) 3)`

`In> UnparseMathPiper('( a / b / c / d ), FullParentheses:True)`
`Result: "(((a/b)/c)/d)"`
`mathjs: (/ (/ (/ a b) c) d)`

`In> UnparseMathPiper('( a * b / c * d ), FullParentheses:True)`
`Result: "((a*(b/c))*d)"`
`mathjs: (* (/ (* a b) c) d)`

`In> UnparseMathPiper('( a * b * c / d ), FullParentheses:True)`
`Result: "((a*b)*(c/d))"`
`mathjs: (/ (* (* a b) c) d)`

**Comment by evykassirer** [comment]
ah, so the first and last are different - I don't think it makes a huge difference :)

**Comment by k4b7** [comment]
So basically the following is true:
- multiplication has higher precedence than division
- multiplication should be flattened but division should **not**
