### ISSUE TITLE
add toTeX function

### ISSUE THREAD

**Issue by k4b7** [kevinbarabash/math-parser#24]
`toTex(parse("x = 5/2"))` should return `x = \frac{5}{2}`

**Comment by k4b7** [comment]
@aliang8 is working on this in https://github.com/kevinbarabash/math-parser/pull/30.

**Comment by aliang8** [comment]
added test cases in the PR

**Comment by k4b7** [comment]
Closed by https://github.com/semantic-math/math-parser/pull/32.  @aliang8 thanks for the PR.
