### ISSUE TITLE
adjust precedence of * and / depending the presence of variables

### ISSUE THREAD

**Issue by k4b7** [kevinbarabash/math-parser#25]
```
parse(2 * x / 4) => ( / ( * 2 x ) 4 )
parse(2 * x / y) => ( / ( * 2 x ) y )
parse(2 * 3 / 4) => ( * 2 ( / 3 4 ) )
parse(x * 3 / 4) => ( * x ( / 3 4 ) )
parse(x * y / 4) => ( * x ( / y 4 ) )
parse( 2 * 3 / x) => ( * 2 ( / 3 x ) )
parse(2 * 3 * x / 4) => ( * 2 ( / ( * 3 x ) 4 ) )
```

**Comment by evykassirer** [comment]
yeahhhh

This is related to the way I look for things to treat as implicit multiplication I think. Does what math-parser does instead break tests?

**Comment by evykassirer** [comment]
(oops I thought this was mathsteps 😅 )

**Comment by k4b7** [comment]
I think the easiest way to address will be a post-processing step.  This will also make it easy to configure this behavior.

**Comment by evykassirer** [comment]
btw do you think this behaviour makes sense? it might be worth changing how mathsteps works if this is a weird inconsistency

**Comment by k4b7** [comment]
@evykassirer it's worth having a discussion about.  I'm trying to minimize the changes to mathsteps while switching parsers.  The change is easy enough, see https://github.com/kevinbarabash/math-parser/commit/297294e78da1d0482b846d252d7d58d91a9580ea.  This is fixed now.
