### ISSUE TITLE
emit `Parentheses` nodes when unnecessary parentheses are encountered

### ISSUE THREAD

**Issue by k4b7** [kevinbarabash/math-parser#26]
e.g.
```
5 + (3*6) =>
{
   type: 'Operation',
   op: 'add',
   args: [
       { type: 'Number', value: '5' },
       { type: 'Parentheses', content: { ... } }
   ]
}          
```

**Comment by k4b7** [comment]
```
(-1)^2 =>
{
   type: 'pow',
   args: [
      { type: 'Apply', op: 'neg', args: [{ type: 'Number', value: '1' }] },
      { type: 'Number', value: '2' },
   ],
}
```
In this case the parens are necessary to describe the expression so they shouldn't be included in the AST.

**Comment by k4b7** [comment]
necessary:
- (-1)^2
- (x+1)^2
- (x*y)^2
- (x^2)^2
- (x+1)/2

unnecessary:
- (5)^2
- (x)^2
- x^(2^2)
- ((x+1)) + 1 // the outer ones are unnecessary
- (x+1) // the expression could be expressed as 'x+1'
- (x)/2

**Comment by aliang8** [comment]
**General Rules for when to insert Parentheses nodes:**
Fixed:
- `(-1)^2` vs `(5)^2`: when base is a positive number
- `((x+1)) + 1`: when the next token is `(`
- `(x+1)^2` vs `(x)^2`: when the base isIdentifier \
- `x^(2^2)`: when the operation is consistent throughout, might not work with minus operation

**Additional cases to consider:**
unnecessary:
- `x + (2 + 2)` <- are these parens necessary?

necessary:
- `x - (2 + 2)`
- `(x + 2)(x + 2)`

**Comment by k4b7** [comment]
> `x + (2 + 2)` <- are these parens necessary?

Good question.  I think there are two different concepts at play:
- can the parsed expression be printed out in it's original form?
- does removing the parentheses change the value of the expression?

For the purposes of adding in explicit `Parentheses` nodes, we're only concerned with the answer to the first question.

With respect to the second question, we'll want to provide functions to flatten things like `x + (2 + 2)` to `x + 2 + 2` and `2 * (x * y)` to `2 * x * y`.  But that seems like a separate issue.

> `((x+1)) + 1`: when the next token is `(`

This isn't quite right because you could have `((x+1)+2) + 1` in which case all the parens are necessary.  In the `((x+1)) + 1` we should check if there are node inside the outer parentheses was wrapped in `(` and `)`... not sure the best way to do this.

**Comment by tkosan** [comment]
@kevinbarabash 

> can the parsed expression be printed out in it's original form?

Would it make sense to save the parse tree if the original form of an expression needed to be worked with instead of placing parentheses in the abstract syntax tree? My understanding of ASTs is they don't explicitly include parentheses.

**Comment by k4b7** [comment]
@tkosan we store the start and end indexes of the substring that results in a particular node.  I'm not sure how helpful storing the substring is though.  If a person wants to print out the original string, they probably have the original string and could just print it out.

TBH, I can't think of a really good reason to keep unnecessary parens are parsing.  We can already describe order of operations by changing the nesting of `add` or `mul` nodes.  Maybe we just don't bother trying to track extra parens and if someone types in:
```
(5)^2
```
we return a structure for
```
5^2
```
and that's it.

@evykassirer I know you had some thoughts about tracking parens.  The AST is able to track things like `(x + 5) + (y + 10)` but is unable to track things like `(5) + 10` or `(x + 5)`.  How big of a deal is it not being able to track the latter two.

cc @aliang8

**Comment by evykassirer** [comment]
for tracking parens, I definitely think the latter is less of a big deal, but there might be some pedagogical value in always telling the user when we remove parens and where we did it - but I'm not sure how big a deal that is or how helpful that'd be 

If it's easy to always make it obvious where parens are being removed, then at least we have the option. But if it's hard, I'd say it's fine to just leave it out. We could even have some way of checking that from the original string to the new AST if there were parens removed (by string equality) and that's probably good enough?
