### ISSUE TITLE
Add support for rule rewrite system

### ISSUE THREAD

**Issue by k4b7** [kevinbarabash/math-parser#27]
Based on discussion from https://github.com/socraticorg/mathsteps/issues/142 I'd like to add support for rule rewriting.  The syntax will be parser dependent, but the hope is that the AST will be parser independent which would allow rules written for one parser to be used with any AST that conforms to [math-ast](https://github.com/kevinbarabash/math-ast) (needs updating).

The goal is to create a functions for defining rules and applying them, e.g.
```
const rule = defineRule('#a #x + #b #x', '(#a + #b) #x', { x: 'Identifier' });
if (canApplyRule(rule, oldTree)) {
    const newTree = applyRule(rule, oldTree);
}
```

The first arg is the input pattern to match.  The second arg is what to transform it into.  The third arg is any constraints on the placeholder nodes.

Currently, I have a very rudimentary matching function that will find the innermost node that matches a particular tree.  There's still a lot to do, but https://github.com/kevinbarabash/math-parser/commit/88d2f0abc5a33af649ab7c86938619b65b5a44bd#diff-8a1bbb60db136cbc4c4cdad4f1582d7a gives an idea of what it's already capable of.

In particular things that need to be handled still are:
- [x] matching sub arrays of children within addition and multiplication nodes
- [ ] being able to match multiplication regardless of whether it's implicit or not, we'll probably want this to be configurable
- [x] enforce constraints
- [x] actually applying the rule
- [ ] deal with children of placeholders, e.g. function names
- [ ] how to describe evaluation in the output of a rule
- [ ] control whether rules are apply from the inside out or the outside in (I think most of the time we want from the inside out so that's what the matcher currently does)

/cc @evykassirer, @aelnaiem, @tkosan

**Comment by evykassirer** [comment]
wooo :)

**Comment by evykassirer** [comment]
> control whether rules are apply from the inside out or the outside in (I think most of the time we want from the inside out so that's what the matcher currently does)

I think it might depend on the rules. Perhaps we can have something that toggles what's being prioritized?

**Comment by k4b7** [comment]
I was able to get some really simple rewrite rules working, e.g. `#a + 0 --> #a` applied to `2 * (x + 0)` produced the result `2 * x`

**Comment by tkosan** [comment]
> how to describe evaluation in the output of a rule

In MathPiper, if the pattern `#a #x + #b #x` in the above rule matched, local variables `a`, `b`, and `x` would be created and the subtree that matched `#a` would be assigned to the variable `a`, the subtree that matched `#b` would be assigned to `b`, and one of the subtrees that matched `#x` would be assigned to `x`. The body of the rule would be defined as `(a + b) x` instead of `(#a + #b) #x`, and this body would be evaluated in the scope of the local variables.

> deal with children of placeholders, e.g. function names

In MathPiper, all of the rewrite rules are held in a global "rulebase" (think database for rules) which is organized by the dominant operator for each rule. Each dominant operator in the global rulebase has its own smaller rulebase that holds all of the rules which are associated with this operator. For example, all rules that have the binary `+` operator as the dominant operator are held in the binary `+` operator's rulebase. Evaluation in MathPiper mostly consists of:
1. Identifying the dominant operator in a subtree of an expression.
2. Obtaining the rulebase for this dominant from the global rulebase.
3. Attempting to match the operands of this operator against each rule in the rulebase until one of them match or none of them match.

> I was able to get some really simple rewrite rules working, e.g. #a + 0 --> #a applied to 2 * (x + 0) produced the result 2 * x

This is exciting!

**Comment by k4b7** [comment]
Baby steps update: 
- rules that rewrite a sub-range of arguments within an add or mul operation work now
- `print` now adds in parentheses as necessary

`2 #a --> #a + #a` applied to `1 + 2 x + 2` produces `1 + (x + x) + 2`

The code is so messy :sob:... I'll fix it later. 😄

**Comment by k4b7** [comment]
> how to describe evaluation in the output of a rule

What I was trying to capture with this item was how to differentiate substitution of expressions from evaluating numeric the output of numeric values.  Looking back at https://github.com/socraticorg/mathsteps/issues/142 I found.

```
x_Number? + y_Number? <-- AddN(x,y);
```

I can do something similar, but I'll need to be able to constraint the types of placeholders first.

**Comment by tkosan** [comment]
I see what you meant now by "placeholders". In MathPiper, an alternative way to define the rule:

`x_Number? + y_Number? <-- AddN(x,y);`

is with what the Yacas developers called a "post predicate":

`x_ + y_ :: Number?(x) &? Number?(y) <-- AddN(x,y);`

The post predicate is the expression that is between the :: and <-- operators. It is evaluated after the pattern to the left of the :: has been matched. If the post predicate evaluates to False, the rule is not applied. (Note: the &? operator in MathPiper is equivalent to JavaScript's && operator).

**Comment by k4b7** [comment]
@tkosan I like the Yacas "post predicate" better because you don't have to repeat the predicate multiple times if you're matching the same subtree in multiple places.  This is captured by the `{ x: 'Identifier' }` optional argument to `defineRule`.

Although I've defined `defineRule` to take strings, I think a version that takes AST nodes should be exposed.  That way different syntax and parsers can reuse the functions for defining and applying rules as long as they use the same AST.

**Comment by k4b7** [comment]
@tkosan some of the change steps from math-steps can involve a variable number of nodes, e.g. collect like terms or distribute.  Is there a way to model these rules in MathPiper or other CASes?

I was thinking something like:
```
#a * (#b_0 + ... + b_n) --> #a * b_0 + ... a# * b_n
```
but I'd have to make a lot of assumptions about things.

Another way might be to provide hooks to call code, e.g.
```
const rule = defineRule("#a * #b", transformFn, { b: isAdd })

const isAdd = node => node.type == 'Operation' && node.op == 'add';
const transformFn = matchedNodes => 
    makeOperation(
        "add", 
        matchedNodes["b"].map(term => makeOperation("mul", [clone(a), clone(b)]),
    );
```

I'm going to give the second option a try because I have a better idea of how I'd implement it.

**Comment by tkosan** [comment]
@kevinbarabash 

> some of the change steps from math-steps can involve a variable number of nodes, e.g. collect like 
> terms or distribute. Is there a way to model these rules in MathPiper or other CASes?

The Wolfram language has the most advanced pattern matching capabilities of any CAS I am aware of, and MathPiper's pattern matcher is based on a subset of it. The Wolfram language is able to match sequences of expressions using the double underscore operator:

https://reference.wolfram.com/language/ref/BlankSequence.html

I have not implemented the double underscore operator in MathPiper yet, so the following is an alternative way to accomplish this task in MathPiper:

```
In> exp := '( 2 * Add(_x, _y, _z) )
Result: 2*Add(_x,_y,_z)

In> exp
Result: 2*Add(_x,_y,_z)

In> FunctionToList(Add(_x, _y, _z))
Result: [+,_x + _y,_z]

In> In> UnFlatten([_a,_b,_c],"+",0)
Result: _a + (_b + _c)

In> exp /: [a_ * b_ :: Type(b) =? "Add" <-  UnFlatten(a * Rest(FunctionToList(b)), "+", 0)]
Result: 2*_x + (2*_y + 2*_z)
```
This appears to be similar to your second option.

**Comment by k4b7** [comment]
@evykassirer what are some change sets (other than distribute and collect like terms) that mathsteps has that involve operating on an array of nodes?

**Comment by k4b7** [comment]
I've implemented the public API of `defineRule`, `canApplyRule`, and `applyRule`.  These functions take ASTs instead of strings.  The constraints parameter passed to `defineRule` takes a dictionary where the values are callbacks that are passed the node being matched to a placeholder, e.g.
```
const isNumber = node => node.type === 'Number'

const rule = defineRuleString('#a #x + #b #x', '(#a + #b) #x', {
    a: isNumber,
    b: isNumber,
})
assert.equal(applyRuleString(rule, '2 x + 3 x'), '(2 + 3) x');
assert.equal(canApplyRuleString(rule, '(a + b) x'), false);
```
The functions with the `String` suffix wrap the public API to accept strings instead of ASTs.

I was thinking that for mathsteps, we'll probably want to be able to apply several rules to the same sets of nodes, so `applyRule` should also return a reference to the node that was updated.  This node could then be used to narrow the scope that the next rule is applied to.

**Comment by k4b7** [comment]
It's now possible to write a rule for distribution across any number of terms.  
```
it('should apply rules with a rewrite callback', () => {
    const rule = defineRuleString(
        '#a #b',
        ({a, b}) => nodes.operationNode(
            'add',
            b.args.map(arg => populatePatternString('#a #arg', {a, arg}))
        ),
        {b: isAdd})

    assert.equal(
        applyRuleString(rule, '3 (x + 1)'),
        '3 x + 3 1')

    assert.equal(
        applyRuleString(rule, '(a - b) (x^2 + 2x + 1)'),
        '(a - b) x^2 + (a - b) 2 x + (a - b) 1')
})
```

**Comment by evykassirer** [comment]
hey Kevin sorry for the delay in response - I'm in MTV now! whee ☀️ 🌴 

> what are some change sets (other than distribute and collect like terms) that mathsteps has that 
involve operating on an array of nodes?

you can see a list of every change type here: https://github.com/socraticorg/mathsteps/blob/master/lib/ChangeTypes.js

I'm not totally sure what you mean by operating on an array of nodes. Most operations are on multiple things (e.g. the args of a node) and therefore involve an array of nodes. Do you mean what rewrite rules would have one/some (but not all) of the left side of the rule being an array of nodes?

**Comment by k4b7** [comment]
"Which change types involve a variable number of nodes" is probably a better way of describing what I was trying to get at.  Changes such as `x + 0 => x` always involve two nodes, but collecting like terms could involve two or more terms if there are lots of terms that can be collected.  In general, I'm trying to get a sense of which types of transforms will push the rule rewrite system.

Another interesting set of changes are those involving gcd/lcm such has reducing fractions to simplest terms or converting a set of fractions to have a common denominator.

**Comment by evykassirer** [comment]
Ah, okay. that makes sense. Does the list of changes with example give you enough to explore that? Nothing immediately comes to mind for me, but I also haven't been thinking of any of these changes as involving rewrite rules while I made them. I'm sure there'll continue to be new challenges coming up even if we think we've thought of everything too ^_^

**Comment by k4b7** [comment]
I've moved this feature to https://github.com/semantic-math/math-rules.  I'll open individual issues for the remaining tasks.
