### ISSUE TITLE
nthRoot(x) test case is failing 

### ISSUE THREAD

**Issue by aliang8** [kevinbarabash/math-parser#54]
![image](https://user-images.githubusercontent.com/16139634/27255123-8402f802-5365-11e7-8940-3b3c274faca8.png)

**Comment by k4b7** [comment]
This is passing on `master`.  Can you provide some more context?  What change results in this failure?

**Comment by aliang8** [comment]
Hmm, I think my `math-parser` version is on a 0.10.3. How can I upgrade it to the most recent version? I tried merging with a remote.

**Comment by aliang8** [comment]
It is happening in my `Integrals` PR.

**Comment by aliang8** [comment]
Resolved as part of https://github.com/semantic-math/math-nodes/commit/a509e935867f213045dc8a7a582db196f9582494
