### ISSUE TITLE
parse "abs(x)"

### ISSUE THREAD

**Issue by evykassirer** [kevinbarabash/math-parser#70]
would be nice to have this as an option as well as `|x|`

**Comment by k4b7** [comment]
This is in 0.13.0 on npm.  Note: we don't store which format was used in the AST so the output for now will always appear as `|x|`.

**Comment by evykassirer** [comment]
that seems fine to me - thanks Kevin :D

**Comment by k4b7** [comment]
I've also updated the demo so you can play around with it, https://semantic-math.github.io/math-parser/?math=abs(x)%20%2B%20%7Cx%7C.
